### ISSUE TITLE
Built-in support for Coil3

### ISSUE THREAD

**Issue by SteinerOk** [saket/telephoto#103]
The library _Coil_ has reached version **3.0.0-rc01** and I think it's a good time to add support out of the box in telephoto

**Comment by saket** [comment]
On it: https://github.com/saket/telephoto/pull/105

**Comment by SteinerOk** [comment]
Hey @saket, I saw you comited support to Coil3, may you release it? :)

**Comment by saket** [comment]
Before I cut a release, do you want to give it a try using `0.14.0-SNAPSHOT`?

**Comment by SteinerOk** [comment]
@saket thanks, I will try!

**Comment by SteinerOk** [comment]
@saket I tried `0.14.0-SNAPSHOT` and I got strange behavior (I'm not sure if it's related to the library, but I'll show it anyway):
- when you rotate the screen with the image in the display without zoom - everything is ok.
- when you rotate the zoomed image - it shifts to the side.

https://github.com/user-attachments/assets/eb06c02d-6bf5-4bdf-8a32-3695be88a25f

This is my code: https://gist.github.com/SteinerOk/1f7bded999e60e9c4cf3c627d6c0bcad

**Comment by saket** [comment]
Could you test if this is a new bug with coil 3, or does it also occur with coil 2?

**Comment by SteinerOk** [comment]
@saket I tested `Coil2+0.14.0-SNAPSHOT` - the same problem, BUT `Coil2+0.13.0` - works fine:

https://github.com/user-attachments/assets/502b72c5-24b7-46b1-9680-c49283b6be49

**Comment by saket** [comment]
Ah okay. I recently made some refactors to `Modifier.zoomable()` which might have caused this. I'll take a look.

**Comment by saket** [comment]
Moving this to https://github.com/saket/telephoto/issues/113

**Comment by saket** [comment]
Released in v0.14.0: https://github.com/saket/telephoto/releases/tag/0.14.0
