### ISSUE TITLE
Zoom and pan transformations aren't retained correctly across orientation changes

### ISSUE THREAD

**Issue by saket** [saket/telephoto#113]
Pasting @SteinerOk's [comment](https://github.com/saket/telephoto/issues/103#issuecomment-2460812374):

> @saket I tried `0.14.0-SNAPSHOT` and I got strange behavior (I'm not sure if it's related to the library, but I'll show it anyway):
> - when you rotate the screen with the image in the display without zoom - everything is ok.
> - when you rotate the zoomed image - it shifts to the side.
> 
> This is my code: https://gist.github.com/SteinerOk/1f7bded999e60e9c4cf3c627d6c0bcad

https://github.com/user-attachments/assets/eb06c02d-6bf5-4bdf-8a32-3695be88a25f

**Comment by saket** [comment]
@SteinerOk does this issue also happen when you change the system theme?

**Comment by saket** [comment]
@SteinerOk this should now be fixed. Could you try 0.14.0-SNAPSHOT again? You'll need to ensure Gradle is using today's snapshot build, possibly by using [pinning](https://medium.com/@vanniktech/pinning-a-snapshot-dependency-to-a-specific-version-b477f79469fc).

**Comment by SteinerOk** [comment]
@saket I tried the new Snapshot version and the specified bug does not reproduce 👍

**Comment by saket** [comment]
Thanks for checking!
