### ISSUE TITLE
Missing APK certificate in release 0.3.0

### ISSUE THREAD

**Issue by SimonMarquis** [saket/telephoto#12]
I wanted to try and install the [APK](https://github.com/saket/telephoto/releases/download/0.3.0/telephoto_sample.apk) you provided for the 0.3.0 release. But it seems the APK has been generated without signing it, making it impossible to install (without manually signing it). Do you mind uploading it signed with a default debug keystore?

FWIW it could be automated in the build pipeline.

**Comment by saket** [comment]
Oh whoops, thanks for flagging this! I added a keystore to prevent this from happening again in the future. Can you try again? 

https://github.com/saket/telephoto/releases/download/0.3.0/telephoto_0.3.0_sample.apk

**Comment by SimonMarquis** [comment]
LGTM, thanks for the quick fix.
