### ISSUE TITLE
ZoomablePDF

### ISSUE THREAD

**Issue by wizarlock** [saket/telephoto#121]
Is there a way to use a Pdf file in ZoomableImage? At the moment, I am converting the file into an image, increasing its bitmap for quality (about 15,000 by 15,000 pixels). It seems strange to me

**Comment by saket** [comment]
You're in luck! I just made some changes to `SubSamplingImage()` that will allow you to render your own bitmaps. Let's move this discussion to https://github.com/saket/telephoto/issues/120?
