### ISSUE TITLE
Support lower sdk version

### ISSUE THREAD

**Issue by ganfra** [saket/telephoto#14]
Hello and thanks for this project! 
However, would that be possible to use a lower sdk version? Or are you relying on some API not available before? 
Would appreciate a `minSdk = 23` (even 21 if nothing prevents it) :-)

**EDIT** `./gradlew check` with `minSdk=23 ` is passing!

**Comment by julioromano** [comment]
Hello Saket, we'd like to include this lib in our OSS project which is `minSdk=23`, hence we quickly drafted [this PR ](https://github.com/saket/telephoto/pull/15)as it seems nothing more is needed. Hope this helps.

**Comment by yuqingweng** [comment]
hello saket ，still have this problem 。when import this，cause error
`the library might be using APIs not available in 23
	Suggestion: use a compatible library with a minSdk of at most 23,
		or increase this project's minSdk version to at least 24,
		or use tools:overrideLibrary="me.saket.telephoto.zoomable.image.coil" to force usage (may lead to runtime failures)`

**Comment by saket** [comment]
Hey everyone! I'm still working on this. Lowering minSdk to 23 [breaks screenshot testing](https://issuetracker.google.com/issues/283219177) so I'm trying to figure out a good workaround.

**Comment by yuqingweng** [comment]
> 嘿大家！我还在研究这个。将 minSdk 降低到 23[会中断屏幕截图测试](https://issuetracker.google.com/issues/283219177)，因此我正在尝试找出一个好的解决方法。

hello saket ，can you release new version after fix it~ thanks

**Comment by saket** [comment]
Yep I'll make a release soon. In the meantime you can unblock yourself by using `0.4.0-SNAPSHOT`.

**Comment by EdricChan03** [comment]
Are there plans to bump it further down to minSdk = 21 if possible to align with [Compose's minSdk requirement](https://developer.android.com/jetpack/compose/setup#create-new)?

**Comment by saket** [comment]
I'm curious to hear your reason for not bumping your min sdk yet. There are fewer than 2% of users using API 21 and 22 devices globally. In some markets, the number is even smaller and not worth catering to IMO.

**Comment by brian512** [comment]
> Are there plans to bump it further down to minSdk = 21 if possible to align with [Compose's minSdk requirement](https://developer.android.com/jetpack/compose/setup#create-new)?

try this:
`<uses-sdk tools:overrideLibrary="me.saket.telephoto.zoomable.image.coil, me.saket.telephoto.subsamplingimage" />`
