### ISSUE TITLE
[Bug] onClick does not work after a double tap zoom gesture

### ISSUE THREAD

**Issue by ammargitham** [saket/telephoto#18]
When using `Modifier.zoomable()`, the onClick is not called if zoomed using double tap.

Sample code:
```kotlin
Image(
    modifier = Modifier
        .fillMaxSize()
        .zoomable(
            state = zoomableState,
            onClick = { _ ->
                Log.d(TAG, "click")
            },
        ),
    painter = it,
    contentDescription = null,
)
```

The above onClick log is printed initially, but after doing a double tap it stop logging a single tap. On debugging it seems the variable `isQuickZooming` remains true even after the zoom animation is completed.

https://github.com/saket/telephoto/blob/5f0ed247d55394832fedc4813e0e53e82f6d6439/zoomable/src/main/kotlin/me/saket/telephoto/zoomable/Zoomable.kt#L92

**Comment by Samuel-Unknown** [comment]
I have the same issue 😢

**Comment by saket** [comment]
I'll make a release with this fix soon. In the meantime y'all can unblock yourself by using `0.4.0-SNAPSHOT`.
