### ISSUE TITLE
Modifier.zoomable() applied separately from ZoomableAsyncImage doesn't force the image to stay in bounds when zoomed-in

### ISSUE THREAD

**Issue by K1rakishou** [saket/telephoto#21]
I tried to apply zoomable to a video player and found out that there is this bug.

MRE:
```
val zoomSpec = remember { ZoomSpec(maxZoomFactor = 3f) }
val zoomableState = rememberZoomableState(zoomSpec = zoomSpec)

// AsyncImage from coil
AsyncImage(
  modifier = modifier
    .zoomable(state = zoomableState),
  model = ImageRequest.Builder(LocalContext.current)
    .data(imageUrl)
    .crossfade(300)
    .build(),
  contentDescription = "",
)
```

[device-2023-05-27-155256.webm](https://github.com/saket/telephoto/assets/10332458/d964504a-0da0-49ca-b910-1a3b852823ef)

It works when using ZoomableAsyncImage, though. Only doesn't work when using Modifier.zoomable() separately. 
Can't tell for sure what might be the cause.

**Comment by saket** [comment]
Are you missing https://saket.github.io/telephoto/zoomable/#edge-detection?

**Comment by K1rakishou** [comment]
Ok I see. Kinda missed that part.

**Comment by saket** [comment]
Yea it is easy to miss. I'll move that section above to the top so that it is slightly more noticeable.
