### ISSUE TITLE
Exif orientation correction

### ISSUE THREAD

**Issue by kmnaseef** [saket/telephoto#30]
Hi,
Thanks for the library. my images orientation is not correct. how i fix using Exif data ?

**Comment by kmnaseef** [comment]
Hi,
  Thanks for the library. my images orientation is not correct. how i fix using Exif data ?

**Comment by saket** [comment]
Possible to share one of your images so that I can test?

**Comment by kmnaseef** [comment]
![Orientation_test](https://github.com/saket/telephoto/assets/13997049/60a48842-3da2-4c92-8336-5daa349263ef)

**Comment by kmnaseef** [comment]
Hi,
 Did you check this?

**Comment by saket** [comment]
Yep. `SubSamplingImage` will need a way to manually rotate images by reading exif information. I'm traveling until mid July. Can try implementing this afterwards.

**Comment by kmnaseef** [comment]
ok

**Comment by saket** [comment]
This is now fixed. Wanna try out `0.5.0-SNAPSHOT` until a stable version is released?

Thanks for reporting!

**Comment by kmnaseef** [comment]
Thank you very much bro

**Comment by kmnaseef** [comment]
how i get the 0.5.0-SNAPSHOT?

**Comment by saket** [comment]
Snapshot versions are hosted on a separate maven repository which will need to be added to your buildscript:

```groovy
repositories {
  google()
  mavenCentral()
  maven {
    url 'https://oss.sonatype.org/content/repositories/snapshots/'
  }
}
```

**Comment by kmnaseef** [comment]
checked.  working.   thanks.
