### ISSUE TITLE
Image can't be panned in reverse after it has reached its edge

### ISSUE THREAD

**Issue by nishankhadka09** [saket/telephoto#33]
If you zoom an image then use your finger to move it up- down or left -right, you can notice that it's not very smooth.

**Comment by saket** [comment]
Can you share a video, and a reproducer if it's not the sample app?

**Comment by nishankhadka09** [comment]
![Screen_recording_20230623_122610](https://github.com/saket/telephoto/assets/118792445/75587832-aa3a-4cb0-b009-c6c1bf1c152c)

**Comment by saket** [comment]
So weird. Please share a reproducer project? I can take a look in some time.

**Comment by nishankhadka09** [comment]
[zoomable.zip](https://github.com/saket/telephoto/files/11844182/zoomable.zip)

**Comment by nishankhadka09** [comment]
I tested with three images, problem happens with image that doesn't fill the screen, like the one above.

**Comment by saket** [comment]
Thanks for reporting this @nishankhadka09! I'll release the fix as part of `0.5.0` soon. In the meantime, you can unblock yourself by using `0.5.0-SNAPSHOT`.
