### ISSUE TITLE
Expose `RelativeContentLocation` as `ZoomableContentLocation.relative`

### ISSUE THREAD

**Issue by AntsyLich** [saket/telephoto#34]
In our use case our `Image` has a `ContentScale.Fit` using that with either `ZoomableContentLocation.scaledInsideAndCenterAligned(canvasSize)` or `ZoomableContentLocation.unscaledAndTopStartAligned(canvasSize)` in `ZoomableState.setContentLocation` gave a weirdly scaled image in case the image is smaller than screen resolution.

Copying the `RelativeContentLocation` from the source code and using `RelativeContentLocation(canvasSize, ContentScale.Fit, Alignment.Center)` gave me the same result i would expect from using `ContentScale.Fit`. This leads me to believe that it is worth to expose a `ZoomableContentLocation.relative` companion function that passes the variables to `RelativeContentLocation` and returns it back as `ZoomableContentLocation`

If accepted I can make a PR

**Comment by saket** [comment]
> … gave a weirdly scaled image in case the image is smaller than screen resolution.

Interesting. `ZoomableImage` uses `scaledInsideAndCenterAligned` to support this same use case -- images that are smaller than layout bounds. Can you share some code, the images you're using and your device resolution?

**Comment by AntsyLich** [comment]
In case of `ZoomableImage` the underline `Image`'s content scale is `ContentScale.Inside` using `ContentScale.Inside` with `scaledInsideAndCenterAligned` doesn't produce any issue but in my case i want to use `ContentScale.Fit` which with `scaledInsideAndCenterAligned` and an image smaller than screen resolution makes the displayed image weirdly zoomed in. In my case I tested with the small image below on a 720x1600 resolution device

![Untitled](https://github.com/saket/telephoto/assets/59261191/7921bf31-beea-406a-b070-4555b7b479c3)

**Comment by AntsyLich** [comment]
@saket any update?

**Comment by saket** [comment]
Sorry, not yet. I'm traveling right now, but can take a look when I'm back
in 2 weeks.

**Comment by saket** [comment]
I tried out the above image on a 720x1600 display but I'm unable to reproduce the problem. @AntsyLich please share a screenshot and some code? A reproducer project would be the best if you've got time. 

```kotlin
ZoomableAsyncImage(
  model = R.drawable.check_pattern,
  contentDescription = …,
  contentScale = ContentScale.Fit,
)
```

![Screenshot_1689732925](https://github.com/saket/telephoto/assets/2387680/0a7e6f4e-c900-490b-bbdc-193042f7bb8e)

**Comment by AntsyLich** [comment]
I also used. 
```kt
var canvasSize by remember { mutableStateOf(Size.Zero) }
LaunchedEffect(canvasSize) {
    if (canvasSize == Size.Zero) return@LaunchedEffect
    zoomState.setContentLocation(
        ZoomableContentLocation.scaledInsideAndCenterAligned(),
    )
}
```
If you still can't reproduce I'll get a reproducible code up

**Comment by saket** [comment]
> If you still can't reproduce I'll get a reproducible code up

Yes please! The code snippet you shared is incomplete. It doesn't show how `canvasSize` is populated.

I'm also curious to know why you aren't using `ZoomableImage` / `ZoomableAsyncImage` directly? Is that because they are incorrectly scaling your image?

**Comment by saket** [comment]
FWIW I've added `ZoomableContentLocation.scaledToFitAndCenterAligned()`, but you shouldn't need to use it if you're using `ZoomableAsyncImage()` / `ZoomableGlideImage()`.

https://github.com/saket/telephoto/blob/d13b51032393949ed768fa6f4251c277d91b2ad3/zoomable/src/commonMain/kotlin/me/saket/telephoto/zoomable/ZoomableContentLocation.kt#L54-L64

It'll be available in the next release.
