### ISSUE TITLE
Support programmatically changing pan/zoom 

### ISSUE THREAD

**Issue by DSteve595** [saket/telephoto#4]
It would be nice to be able to programmatically manipulate the transformation of the image, initially and over time.
Use cases:
- A comic reader wants to start at the top, probably one of the corners
- A map wants to start viewing a specific location

**Comment by saket** [comment]
@DSteve595

**Comment by nateridderman** [comment]
> A map wants to start viewing a specific location

💯 this is my use case. This library is awesome, and this issue is the one thing it's missing before I can adopt it in my app.

**Comment by saket** [comment]
The next release will introduce new APIs for controlling an image's pan and zoom. @nateridderman will this solve your use case?

https://github.com/saket/telephoto/blob/f0201b80d627ba1950ee460db14c132b3406e553/zoomable/src/commonMain/kotlin/me/saket/telephoto/zoomable/ZoomableState.kt#L146-L190
