### ISSUE TITLE
Incorrect alignment of images in RTL layout direction

### ISSUE THREAD

**Issue by MV-GH** [saket/telephoto#44]
One of my users reported this issue https://github.com/dessalines/jerboa/issues/1212. In which the image viewer does not always properly center the image in ContentScale.Fit when it is set to RTL. Which does work with LTR.

I made a repro

![image](https://github.com/saket/telephoto/assets/67873169/83b292eb-c881-4b39-a30f-8b485bf7704e)

This image is supposed to be completed stretched on the horizontal

see repro https://github.com/MV-GH/ReproChannelCrash/tree/rtl_bug

**Comment by saket** [comment]
This was a fun bug to fix. Thanks for sending these bug reports @MV-GH. Please keep em coming!

I'll make a new release soon, but in the meantime you can use `0.6.0-SNAPSHOT` once this action finishes running: https://github.com/saket/telephoto/actions/runs/6069596982.
