### ISSUE TITLE
Loading of bitmap tiles occasionally stops working in 0.6.0

### ISSUE THREAD

**Issue by saket** [saket/telephoto#46]
Continuing the discussion from https://github.com/saket/telephoto/issues/39#issuecomment-1707118611 cc @mv-gh

**Comment by saket** [comment]
@MV-GH could you please try out these two APKs and see if you can reproduce the issue?

https://drive.google.com/file/d/1Rjzrc-vEPN_BuLa8VGYHPPw7Tn9M8i6K/view?usp=sharing

https://drive.google.com/file/d/1zcVrtHwmAUYWW45DaSoVOk985flkbvLG/view?usp=sharing

The second image is the same one as you're using in https://github.com/MV-GH/ReproChannelCrash/

**Comment by MV-GH** [comment]
Sure but I am traveling rn. I'll take a look when i find some time.

**Comment by MV-GH** [comment]
I can no longer reproduce this, not sure what changed with last week where I could consistently reproduce it. You can close it. I'll reopen whenever I am able to reproduce it.

I took a look at the APKs. They seem to work fine bit annoying to zoom in emulator as it keeps swiping to the next image.

Also that one image in the APK, doesn't seem to sharpen at all but is not zoomable either

see vid below

https://github.com/saket/telephoto/assets/67873169/53a30c44-4d13-4e07-8faa-246784594293

**Comment by saket** [comment]
Ah okay. Thanks for checking!

The first two images are gigantic in size so you'll have to wait for a minute or two before they load, depending on your network condition.
