### ISSUE TITLE
Exif image rotation for ZoomableAsyncImage w/ coil

### ISSUE THREAD

**Issue by hvisser** [saket/telephoto#48]
When swapping out `AsyncImage` with `ZoomableAsyncImage` exif rotation seems to be ignored. `AsyncImage` shows my image in the correct orientation, while `ZoomableAsyncImage` does not. 

I saw https://github.com/saket/telephoto/issues/30 marked as fixed so this might have regressed (or never worked for Coil)?

**Comment by saket** [comment]
Will you be able to share a sample image? I've got a [few here](https://github.com/saket/telephoto/tree/trunk/zoomable-image/sub-sampling-image/src/androidTest/assets) but it's possible I'm missing something. 

Exif rotation is applied by the [bitmap decoder](https://github.com/saket/telephoto/blob/fc69b6a586f9b2a0165111fc3ad7b5aed1d748e1/zoomable-image/sub-sampling-image/src/main/kotlin/me/saket/telephoto/subsamplingimage/internal/AndroidImageRegionDecoder.kt#L44) so it should work for all image libraries out of the box

**Comment by hvisser** [comment]
Ah OK, that was added after `1.0.0-alpha02` though which I was using. With the `0.6.0-SNAPSHOT` (and `0.5.0`) the rotation is correct.

I guess the confusion is that that release even exists as the docs etc do point to `0.5.0`. I didn't see that so I did a maven search and picked the "latest" version.

**Comment by saket** [comment]
Yea sorry about that. My decision to release a `1.x.x-alpha` and then go back to using `0.x` was a mistake.

**Comment by hvisser** [comment]
No worries, it's a great library so thanks for that!
