### ISSUE TITLE
New Feature: Min & Max Zoom Level

### ISSUE THREAD

**Issue by devs-gireeb** [saket/telephoto#55]
I suggest adding **_min_** and **_max_** zoom options to image component for better UX.
This would let us control zoom levels, ensuring a smoother experience.

Ex:
minZoom: Float = 1f,
maxZoom: Float = 5f

**Comment by saket** [comment]
Does this help?

```kotlin
val state = rememberZoomableState(
  zoomSpec = ZoomSpec(maxZoomFactor = 5f)
)
```

**Comment by devs-gireeb** [comment]
> Does this help?
> 
> ```kotlin
> val state = rememberZoomableState(
>   zoomSpec = ZoomSpec(maxZoomFactor = 5f)
> )
> ```

Certainly helpful , Thank you @saket
