### ISSUE TITLE
Difficult to zoom inside pager

### ISSUE THREAD

**Issue by kmnaseef** [saket/telephoto#60]
https://github.com/saket/telephoto/assets/13997049/79ec8ea4-0571-49f5-b235-d299fab30113

While trying to pinch zoom ZoomableAsyncImage used inside a HorizontalPager/VerticalPager, most of the time the pager changes the page instead of zooming. How I overcome this issue?

**Comment by saket** [comment]
Can this be reproduced in the sample by replacing the `HorizontalPager` with a `VerticalPager`? https://github.com/saket/telephoto/blob/d8c19c77fe58f8cbff4dd0ac1904a176a61aa64c/sample/src/main/kotlin/me/saket/telephoto/sample/viewer/MediaViewerScreen.kt#L45

**Comment by kmnaseef** [comment]
yea. have the same issue for verticalPager also. only the direction changes.
is it possible to introduce a threshold to the horizontalPager/verticalPager for detecting drag?

**Comment by saket** [comment]
Can you share a video of telephoto's [sample app](https://github.com/saket/telephoto/blob/12c09356d0820c54f33669d94ce68365425f73af/sample/src/main/kotlin/me/saket/telephoto/sample/viewer/MediaViewerScreen.kt#L55) with this problem? I can't seem to reproduce it.

**Comment by saket** [comment]
> most of the time the pager changes the page instead of zooming

Here's a different theory: is this issue happening only when the placeholder image is visible? You can confirm this by adding a loading indicator while the full image is loading:

```kotlin
if (!imageState.isImageDisplayed) {
  CircularProgressIndicator()
}
```

**Comment by kmnaseef** [comment]
Sorry for late reply. Problem exist for telephoto app also.

https://github.com/saket/telephoto/assets/13997049/5925d964-5cd4-46d8-beea-3d00f0563ddb

**Comment by saket** [comment]
Thanks @kmnaseef! I made a small improvement to consume gestures immediately if multiple fingers/pointers are detected in https://github.com/saket/telephoto/commit/4c9118e1680efafc2c6b7b33319f2e281dfc7532. Can you give `0.8.0-SNAPSHOT` a try?

**Comment by kmnaseef** [comment]
Perfect bro... thank you very much..

**Comment by saket** [comment]
FWIW I filed a bug report against Compose UI because I believe the bug lies inside `Modifier.transformable()`: https://issuetracker.google.com/issues/325807994.
