### ISSUE TITLE
Keyboard support

### ISSUE THREAD

**Issue by evant** [saket/telephoto#78]
This is probably most important for desktop usage but can also be useful on mobile if you have an external keyboard connected.

I would expect this to work out of the box:
ctrl+, ctrl-, ctrl0 to control zoom
arrow keys to pan when zoomed

**Comment by saket** [comment]
Good idea! I've been wanting to add an API for controlling the zoom and pan from code (https://github.com/saket/telephoto/issues/4). This would be a nice follow-up to that.

**Comment by saket** [comment]
Released in `0.12.0`: https://github.com/saket/telephoto/releases/tag/0.12.0
