### ISSUE TITLE
Add mouse wheel zoom support

### ISSUE THREAD

**Issue by alexvanyo** [saket/telephoto#87]
Related to #78, the scroll wheel of a mouse should also zoom in and out.

**Comment by saket** [comment]
Just to confirm, is this for Android?

**Comment by alexvanyo** [comment]
Correct, either via the mouse wheel from a connected physical mouse, or from a trackpad like with a Chromebook or tablet.

**Comment by saket** [comment]
TIL you can zoom using the scroll wheel without pressing any modifier/meta keys on android

https://github.com/saket/telephoto/assets/2387680/8f3a4de7-4af0-4305-a8f2-b8a1b59b466e

**Comment by saket** [comment]
[Done](https://github.com/saket/telephoto/blob/b9c71727c6fe8f47b33cb05b3b51d992e83ed889/zoomable/src/commonMain/kotlin/me/saket/telephoto/zoomable/internal/DefaultHardwareShortcutDetector.kt#L58-L77). Thanks for the suggestion @alexvanyo!

**Comment by saket** [comment]
Released in `0.12.0`: https://github.com/saket/telephoto/releases/tag/0.12.0
