### ISSUE TITLE
Lower minSDK to 21

### ISSUE THREAD

**Issue by iwb-florien-flament** [saket/telephoto#91]
Even if there's a very low number of devices still running on Android Lollipop, the current price to pay to lower the minSDK of the library is quite low.
The only place where it need a change is the haptic feedback for Android. This could be easily overridden for the 21/22 SDK

**Comment by iwb-florien-flament** [comment]
You can take a look at the implementation needed in [this PR](https://github.com/saket/telephoto/pull/92)

**Comment by saket** [comment]
Sure, let's do it!

**Comment by iwb-florien-flament** [comment]
Thanks a lot ! 🙇

**Comment by iwb-florien-flament** [comment]
Hello @saket 👋 

Would it be possible to have an estimation on when a new release with this issue's code will be released ? In order to plan accordingly the development in our project.

Thanks already !

**Comment by saket** [comment]
Yea sorry, I've been meaning to do it for the last two weeks, but my travels have kept me occupied. I'm now planning to make the release this weekend.

**Comment by saket** [comment]
Done: https://github.com/saket/telephoto/releases/tag/0.12.0
