### ISSUE TITLE
FileNotFoundException crashes app

### ISSUE THREAD

**Issue by savvasdalkitsis** [saket/telephoto#99]
I am getting a couple of crashes in UhuruPhotos (https://github.com/savvasdalkitsis/uhuruphotos-android/issues/976) relating to telephoto. I believe the cause issue could be that the app somehow thinks there is a local media file on disk to display and it tries to load it with telephoto, so there is something to be fixed there for sure but I still think that perhaps the library shouldn't crash when the file it tries to load is missing but perhaps handle it more graciously?

Thoughts?

```
java.io.FileNotFoundException · java.io.FileNotFoundException: No item at content://media/external/images/media/1000251914
RawDatabaseUtils.java:151
android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcelContentProviderNative.java:814
android.content.ContentProviderProxy.openTypedAssetFileContentResolver.java:2043
android.content.ContentResolver.openTypedAssetFileDescriptorContentResolver.java:1858
android.content.ContentResolver.openAssetFileDescriptorContentResolver.java:1528
android.content.ContentResolver.openInputStreamSubSamplingImageSource.kt:213
me.saket.telephoto.subsamplingimage.UriImageSource.peeksubSamplingEligibility.kt:47
me.saket.telephoto.zoomable.coil.SubSamplingEligibilityKt.canBeSubSampledsubSamplingEligibility.kt:1
me.saket.telephoto.zoomable.coil.SubSamplingEligibilityKt.access$canBeSubSampledsubSamplingEligibility.kt:27
me.saket.telephoto.zoomable.coil.SubSamplingEligibilityKt$canBeSubSampled$2.invokeSuspendContinuationImpl.kt:33
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWithDispatchedTask.kt:104
kotlinx.coroutines.DispatchedTask.run
```

**Comment by saket** [comment]
Oh yea, I think I'm incorrectly assuming that content Uris will always be available. I'll fix this once I'm back home in a few days. 

https://github.com/saket/telephoto/blob/676b0da0ddf362a693881a166bd48f5556a91379/zoomable-image/coil/src/main/kotlin/me/saket/telephoto/zoomable/coil/CoilImageSource.kt#L193-L198

**Comment by saket** [comment]
I’m back at my computer today and was able to reproduce the issue, but only under specific conditions: when the image has been deleted from the disk but remains in Coil’s memory cache. Could this be what’s happening with your users?

Regression test: https://github.com/saket/telephoto/commit/dd794df0fb8a007d8e92abab9707bb54071e592b#diff-fc5fbc64d3d34d4b964b17bcdc367ce908897e49ae96a394ac9bd5f7957cb193

**Comment by savvasdalkitsis** [comment]
Possibly. this doesn't happen frequently so i have no way to check tbh.

**Comment by EvgenyMeltsaykin** [comment]
@saket Hi! I have this happen all the time on my work project. It doesn't happen on all devices, but I can replicate it on a Galaxy A6+ I can check the snapshot version with the fix if you can provide it to me

**Comment by saket** [comment]
@EvgenyMeltsaykin that'd be super helpful. Can you try out `0.14.0-SNAPSHOT`?

**Comment by saket** [comment]
0.14.0 is out with a fix: https://github.com/saket/telephoto/releases/tag/0.14.0. Please let me know if you continue seeing these crashes?
